import { BeerTypes } from '../enum/beer-types.enum';
import { Beer } from '../interfaces/beer.interface';

export const BEER_LIST_ONE: Beer[] = [
  {
    id: 1,
    name: 'Münchner Gold',
    type: BeerTypes.PILSNER,
    description:
      'Cerveja clara e refrescante com notas de malte e lúpulo nobre, finalização limpa e cítrica.',
    imgPath: 'https://picsum.photos/seed/pilsner1/300/200',
    abv: 4.8,
    ibu: 25,
    price: 12.9,
    quantity: 8,
  },
  {
    id: 2,
    name: 'Pilsner da Serra',
    type: BeerTypes.PILSNER,
    description:
      'Pilsen brasileira premium, leve e cristalina, com aroma floral e sabor equilibrado.',
    imgPath: 'https://picsum.photos/seed/pilsner2/300/200',
    abv: 4.5,
    ibu: 22,
    price: 11.9,
    quantity: 5,
  },
  {
    id: 3,
    name: 'Hop Monster IPA',
    type: BeerTypes.IPA,
    description:
      'IPA encorpada com intenso aroma de lúpulos americanos, notas de frutas tropicais e pinho.',
    imgPath: 'https://picsum.photos/seed/ipa1/300/200',
    abv: 6.8,
    ibu: 65,
    price: 18.9,
    quantity: 3,
  },
  {
    id: 4,
    name: 'Carioca IPA',
    type: BeerTypes.IPA,
    description:
      'IPA tropical com manga e maracujá, perfeita harmonia entre amargor e frutas brasileiras.',
    imgPath: 'https://picsum.photos/seed/ipa2/300/200',
    abv: 6.2,
    ibu: 55,
    price: 17.9,
    quantity: 7,
  },
  {
    id: 5,
    name: 'Schwarzbier Nights',
    type: BeerTypes.STOUT,
    description:
      'Stout robusta com notas intensas de café torrado e chocolate amargo.',
    imgPath: 'https://picsum.photos/seed/stout1/300/200',
    abv: 5.8,
    ibu: 35,
    price: 15.9,
    quantity: 2,
  },
  {
    id: 6,
    name: 'Café com Leite Stout',
    type: BeerTypes.STOUT,
    description:
      'Milk stout cremosa com adição de café especial brasileiro, suave e aveludada.',
    imgPath: 'https://picsum.photos/seed/stout2/300/200',
    abv: 6.0,
    ibu: 30,
    price: 16.9,
    quantity: 4,
  },
  {
    id: 7,
    name: 'Weißbier Traditional',
    type: BeerTypes.WEISS,
    description:
      'Cerveja de trigo alemã com notas de banana e cravo, refrescante e turva.',
    imgPath: 'https://picsum.photos/seed/weiss1/300/200',
    abv: 5.2,
    ibu: 12,
    price: 14.9,
    quantity: 6,
  },
  {
    id: 8,
    name: 'Trigo da Fazenda',
    type: BeerTypes.WEISS,
    description:
      'Weissbier brasileira com trigo local, leve e aromática com toques cítricos.',
    imgPath: 'https://picsum.photos/seed/weiss2/300/200',
    abv: 5.0,
    ibu: 15,
    price: 13.9,
    quantity: 9,
  },
  {
    id: 9,
    name: 'Kellerbier Original',
    type: BeerTypes.LAGER,
    description:
      'Lager não filtrada no estilo alemão, sabor rico em malte com final seco.',
    imgPath: 'https://picsum.photos/seed/lager1/300/200',
    abv: 5.2,
    ibu: 20,
    price: 13.9,
    quantity: 3,
  },
  {
    id: 10,
    name: 'Lager da Praia',
    type: BeerTypes.LAGER,
    description:
      'Lager leve e dourada, perfeita para o clima tropical, com notas sutis de malte.',
    imgPath: 'https://picsum.photos/seed/lager2/300/200',
    abv: 4.7,
    ibu: 18,
    price: 11.9,
    quantity: 8,
  },
];

export const BEER_LIST_TWO: Beer[] = [
  {
    id: 1,
    name: 'Bohemian Pilsner',
    type: BeerTypes.PILSNER,
    description:
      'Clássica pilsner tcheca com malte moraviano e lúpulo Saaz, sabor refinado e amargor elegante.',
    imgPath: 'https://picsum.photos/seed/pilsner3/300/200',
    abv: 4.9,
    ibu: 28,
    price: 14.9,
    quantity: 5,
  },
  {
    id: 2,
    name: 'Alpine Pilsner',
    type: BeerTypes.PILSNER,
    description:
      'Pilsner inspirada nos Alpes, cristalina e refrescante com notas herbais.',
    imgPath: 'https://picsum.photos/seed/pilsner4/300/200',
    abv: 5.0,
    ibu: 26,
    price: 13.9,
    quantity: 7,
  },
  {
    id: 3,
    name: 'West Coast IPA',
    type: BeerTypes.IPA,
    description:
      'IPA americana intensa com blend de lúpulos do Pacífico, notas de pinho e citrus.',
    imgPath: 'https://picsum.photos/seed/ipa3/300/200',
    abv: 7.2,
    ibu: 70,
    price: 19.9,
    quantity: 4,
  },
  {
    id: 4,
    name: 'Hazy Tropical IPA',
    type: BeerTypes.IPA,
    description: 'New England IPA nebulosa com manga, maracujá e abacaxi.',
    imgPath: 'https://picsum.photos/seed/ipa4/300/200',
    abv: 6.5,
    ibu: 45,
    price: 18.9,
    quantity: 6,
  },
  {
    id: 5,
    name: 'Imperial Stout',
    type: BeerTypes.STOUT,
    description: 'Stout imperial potente com notas de cacau, café e baunilha.',
    imgPath: 'https://picsum.photos/seed/stout3/300/200',
    abv: 9.0,
    ibu: 60,
    price: 22.9,
    quantity: 2,
  },
  {
    id: 6,
    name: 'Oatmeal Stout',
    type: BeerTypes.STOUT,
    description:
      'Stout aveludada com aveia, sabores de chocolate ao leite e caramelo.',
    imgPath: 'https://picsum.photos/seed/stout4/300/200',
    abv: 5.5,
    ibu: 28,
    price: 16.9,
    quantity: 5,
  },
  {
    id: 7,
    name: 'Bavarian Weiss',
    type: BeerTypes.WEISS,
    description:
      'Weissbier bávara tradicional com forte perfil de banana e cravo.',
    imgPath: 'https://picsum.photos/seed/weiss3/300/200',
    abv: 5.4,
    ibu: 14,
    price: 15.9,
    quantity: 7,
  },
  {
    id: 8,
    name: 'Summer Weiss',
    type: BeerTypes.WEISS,
    description: 'Cerveja de trigo leve e cítrica, perfeita para o verão.',
    imgPath: 'https://picsum.photos/seed/weiss4/300/200',
    abv: 4.8,
    ibu: 12,
    price: 14.9,
    quantity: 8,
  },
  {
    id: 9,
    name: 'Vienna Lager',
    type: BeerTypes.LAGER,
    description:
      'Lager austríaca com maltes especiais, cor âmbar e sabor maltado.',
    imgPath: 'https://picsum.photos/seed/lager3/300/200',
    abv: 5.3,
    ibu: 22,
    price: 14.9,
    quantity: 38,
  },
  {
    id: 10,
    name: 'Helles Lager',
    type: BeerTypes.LAGER,
    description: 'Lager alemã dourada e límpida com maltes premium.',
    imgPath: 'https://picsum.photos/seed/lager4/300/200',
    abv: 4.9,
    ibu: 18,
    price: 13.9,
    quantity: 50,
  },
];

export const BEER_LIST_THREE: Beer[] = [
  {
    id: 1,
    name: 'Noble Pilsner',
    type: BeerTypes.PILSNER,
    description:
      'Pilsner premium com lúpulos nobres europeus e maltes selecionados.',
    imgPath: 'https://picsum.photos/seed/pilsner5/300/200',
    abv: 5.1,
    ibu: 30,
    price: 15.9,
    quantity: 42,
  },
  {
    id: 2,
    name: 'Crystal Pilsner',
    type: BeerTypes.PILSNER,
    description:
      'Pilsner extra clara e cristalina com final seco e refrescante.',
    imgPath: 'https://picsum.photos/seed/pilsner6/300/200',
    abv: 4.7,
    ibu: 25,
    price: 12.9,
    quantity: 55,
  },
  {
    id: 3,
    name: 'Double IPA',
    type: BeerTypes.IPA,
    description:
      'IPA dupla explosiva com lúpulos raros e aroma intenso de frutas tropicais.',
    imgPath: 'https://picsum.photos/seed/ipa5/300/200',
    abv: 8.5,
    ibu: 85,
    price: 23.9,
    quantity: 20,
  },
  {
    id: 4,
    name: 'Session IPA',
    type: BeerTypes.IPA,
    description: 'IPA leve e sessionável com notas cítricas e final limpo.',
    imgPath: 'https://picsum.photos/seed/ipa6/300/200',
    abv: 4.5,
    ibu: 40,
    price: 16.9,
    quantity: 48,
  },
  {
    id: 5,
    name: 'Chocolate Stout',
    type: BeerTypes.STOUT,
    description:
      'Stout com cacau orgânico, notas intensas de chocolate amargo.',
    imgPath: 'https://picsum.photos/seed/stout5/300/200',
    abv: 6.2,
    ibu: 35,
    price: 17.9,
    quantity: 30,
  },
  {
    id: 6,
    name: 'Coconut Stout',
    type: BeerTypes.STOUT,
    description: 'Stout tropical com coco torrado e baunilha natural.',
    imgPath: 'https://picsum.photos/seed/stout6/300/200',
    abv: 6.0,
    ibu: 32,
    price: 18.9,
    quantity: 25,
  },
  {
    id: 7,
    name: 'Dunkel Weiss',
    type: BeerTypes.WEISS,
    description:
      'Weissbier escura com maltes torrados e especiarias tradicionais.',
    imgPath: 'https://picsum.photos/seed/weiss5/300/200',
    abv: 5.3,
    ibu: 15,
    price: 15.9,
    quantity: 35,
  },
  {
    id: 8,
    name: 'Honey Weiss',
    type: BeerTypes.WEISS,
    description: 'Cerveja de trigo com mel silvestre, suave e aromática.',
    imgPath: 'https://picsum.photos/seed/weiss6/300/200',
    abv: 5.0,
    ibu: 13,
    price: 16.9,
    quantity: 40,
  },
  {
    id: 9,
    name: 'Czech Lager',
    type: BeerTypes.LAGER,
    description: 'Lager tcheca tradicional com malte Moravia e lúpulo Saaz.',
    imgPath: 'https://picsum.photos/seed/lager5/300/200',
    abv: 4.8,
    ibu: 24,
    price: 14.9,
    quantity: 45,
  },
  {
    id: 10,
    name: 'Dark Lager',
    type: BeerTypes.LAGER,
    description: 'Lager escura com notas de caramelo e torrado suave.',
    imgPath: 'https://picsum.photos/seed/lager6/300/200',
    abv: 5.0,
    ibu: 20,
    price: 15.9,
    quantity: 35,
  },
];
