import { BeerTypes } from '../enum/beer-types.enum';
import { Beer } from '../interfaces/beer.interface';

export const getBeerListOne = (breweryId: number): Beer[] => [
  {
    id: 1,
    breweryId,
    name: 'Münchner Gold',
    type: BeerTypes.PILSNER,
    description:
      'Cerveja clara e refrescante com notas de malte e lúpulo nobre, finalização limpa e cítrica.',
    imgPath: 'assets/imgs/beers/imagem_pilsner.png',
    abv: 4.8,
    ibu: 25,
    price: 12.9,
    quantity: 8,
  },
  {
    id: 2,
    breweryId,
    name: 'Pilsner da Serra',
    type: BeerTypes.PILSNER,
    description:
      'Pilsen brasileira premium, leve e cristalina, com aroma floral e sabor equilibrado.',
    imgPath: 'assets/imgs/beers/imagem_pilsner.png',
    abv: 4.5,
    ibu: 22,
    price: 11.9,
    quantity: 5,
  },
  {
    id: 3,
    breweryId,
    name: 'Hop Monster IPA',
    type: BeerTypes.IPA,
    description:
      'IPA encorpada com intenso aroma de lúpulos americanos, notas de frutas tropicais e pinho.',
    imgPath: 'assets/imgs/beers/imagem_ipa.png',
    abv: 6.8,
    ibu: 65,
    price: 18.9,
    quantity: 3,
  },
  {
    id: 4,
    breweryId,
    name: 'Carioca IPA',
    type: BeerTypes.IPA,
    description:
      'IPA tropical com manga e maracujá, perfeita harmonia entre amargor e frutas brasileiras.',
    imgPath: 'assets/imgs/beers/imagem_ipa.png',
    abv: 6.2,
    ibu: 55,
    price: 17.9,
    quantity: 7,
  },
  {
    id: 5,
    breweryId,
    name: 'Schwarzbier Nights',
    type: BeerTypes.STOUT,
    description:
      'Stout robusta com notas intensas de café torrado e chocolate amargo.',
    imgPath: 'assets/imgs/beers/imagem_stout.png',
    abv: 5.8,
    ibu: 35,
    price: 15.9,
    quantity: 2,
  },
  {
    id: 6,
    breweryId,
    name: 'Café com Leite Stout',
    type: BeerTypes.STOUT,
    description:
      'Milk stout cremosa com adição de café especial brasileiro, suave e aveludada.',
    imgPath: 'assets/imgs/beers/imagem_stout.png',
    abv: 6.0,
    ibu: 30,
    price: 16.9,
    quantity: 4,
  },
  {
    id: 7,
    breweryId,
    name: 'Weißbier Traditional',
    type: BeerTypes.WEISS,
    description:
      'Cerveja de trigo alemã com notas de banana e cravo, refrescante e turva.',
    imgPath: 'assets/imgs/beers/imagem_weiss.png',
    abv: 5.2,
    ibu: 12,
    price: 14.9,
    quantity: 6,
  },
  {
    id: 8,
    breweryId,
    name: 'Trigo da Fazenda',
    type: BeerTypes.WEISS,
    description:
      'Weissbier brasileira com trigo local, leve e aromática com toques cítricos.',
    imgPath: 'assets/imgs/beers/imagem_weiss.png',
    abv: 5.0,
    ibu: 15,
    price: 13.9,
    quantity: 9,
  },
  {
    id: 9,
    breweryId,
    name: 'Kellerbier Original',
    type: BeerTypes.LAGER,
    description:
      'Lager não filtrada no estilo alemão, sabor rico em malte com final seco.',
    imgPath: 'assets/imgs/beers/imagem_lager.png',
    abv: 5.2,
    ibu: 20,
    price: 13.9,
    quantity: 3,
  },
  {
    id: 10,
    breweryId,
    name: 'Lager da Praia',
    type: BeerTypes.LAGER,
    description:
      'Lager leve e dourada, perfeita para o clima tropical, com notas sutis de malte.',
    imgPath: 'assets/imgs/beers/imagem_lager.png',
    abv: 4.7,
    ibu: 18,
    price: 11.9,
    quantity: 8,
  },
];

export const getBeerListTwo = (breweryId: number): Beer[] => [
  {
    id: 11,
    breweryId,
    name: 'Bohemian Pilsner',
    type: BeerTypes.PILSNER,
    description:
      'Clássica pilsner tcheca com malte moraviano e lúpulo Saaz, sabor refinado e amargor elegante.',
    imgPath: 'assets/imgs/beers/imagem_pilsner.png',
    abv: 4.9,
    ibu: 28,
    price: 14.9,
    quantity: 5,
  },
  {
    id: 12,
    breweryId,
    name: 'Alpine Pilsner',
    type: BeerTypes.PILSNER,
    description:
      'Pilsner inspirada nos Alpes, cristalina e refrescante com notas herbais.',
    imgPath: 'assets/imgs/beers/imagem_pilsner.png',
    abv: 5.0,
    ibu: 26,
    price: 13.9,
    quantity: 7,
  },
  {
    id: 13,
    breweryId,
    name: 'West Coast IPA',
    type: BeerTypes.IPA,
    description:
      'IPA americana intensa com blend de lúpulos do Pacífico, notas de pinho e citrus.',
    imgPath: 'assets/imgs/beers/imagem_ipa.png',
    abv: 7.2,
    ibu: 70,
    price: 19.9,
    quantity: 4,
  },
  {
    id: 14,
    breweryId,
    name: 'Hazy Tropical IPA',
    type: BeerTypes.IPA,
    description: 'New England IPA nebulosa com manga, maracujá e abacaxi.',
    imgPath: 'assets/imgs/beers/imagem_ipa.png',
    abv: 6.5,
    ibu: 45,
    price: 18.9,
    quantity: 6,
  },
  {
    id: 15,
    breweryId,
    name: 'Imperial Stout',
    type: BeerTypes.STOUT,
    description: 'Stout imperial potente com notas de cacau, café e baunilha.',
    imgPath: 'assets/imgs/beers/imagem_stout.png',
    abv: 9.0,
    ibu: 60,
    price: 22.9,
    quantity: 2,
  },
  {
    id: 16,
    breweryId,
    name: 'Oatmeal Stout',
    type: BeerTypes.STOUT,
    description:
      'Stout aveludada com aveia, sabores de chocolate ao leite e caramelo.',
    imgPath: 'assets/imgs/beers/imagem_stout.png',
    abv: 5.5,
    ibu: 28,
    price: 16.9,
    quantity: 5,
  },
  {
    id: 17,
    breweryId,
    name: 'Bavarian Weiss',
    type: BeerTypes.WEISS,
    description:
      'Weissbier bávara tradicional com forte perfil de banana e cravo.',
    imgPath: 'assets/imgs/beers/imagem_weiss.png',
    abv: 5.4,
    ibu: 14,
    price: 15.9,
    quantity: 7,
  },
  {
    id: 18,
    breweryId,
    name: 'Summer Weiss',
    type: BeerTypes.WEISS,
    description: 'Cerveja de trigo leve e cítrica, perfeita para o verão.',
    imgPath: 'assets/imgs/beers/imagem_weiss.png',
    abv: 4.8,
    ibu: 12,
    price: 14.9,
    quantity: 8,
  },
  {
    id: 19,
    breweryId,
    name: 'Vienna Lager',
    type: BeerTypes.LAGER,
    description:
      'Lager austríaca com maltes especiais, cor âmbar e sabor maltado.',
    imgPath: 'assets/imgs/beers/imagem_lager.png',
    abv: 5.3,
    ibu: 22,
    price: 14.9,
    quantity: 38,
  },
  {
    id: 20,
    breweryId,
    name: 'Helles Lager',
    type: BeerTypes.LAGER,
    description: 'Lager alemã dourada e límpida com maltes premium.',
    imgPath: 'assets/imgs/beers/imagem_lager.png',
    abv: 4.9,
    ibu: 18,
    price: 13.9,
    quantity: 50,
  },
];

export const getBeerListThree = (breweryId: number): Beer[] => [
  {
    id: 21,
    breweryId,
    name: 'Noble Pilsner',
    type: BeerTypes.PILSNER,
    description:
      'Pilsner premium com lúpulos nobres europeus e maltes selecionados.',
    imgPath: 'assets/imgs/beers/imagem_pilsner.png',
    abv: 5.1,
    ibu: 30,
    price: 15.9,
    quantity: 42,
  },
  {
    id: 22,
    breweryId,
    name: 'Crystal Pilsner',
    type: BeerTypes.PILSNER,
    description:
      'Pilsner extra clara e cristalina com final seco e refrescante.',
    imgPath: 'assets/imgs/beers/imagem_pilsner.png',
    abv: 4.7,
    ibu: 25,
    price: 12.9,
    quantity: 55,
  },
  {
    id: 23,
    breweryId,
    name: 'Double IPA',
    type: BeerTypes.IPA,
    description:
      'IPA dupla explosiva com lúpulos raros e aroma intenso de frutas tropicais.',
    imgPath: 'assets/imgs/beers/imagem_ipa.png',
    abv: 8.5,
    ibu: 85,
    price: 23.9,
    quantity: 20,
  },
  {
    id: 24,
    breweryId,
    name: 'Session IPA',
    type: BeerTypes.IPA,
    description: 'IPA leve e sessionável com notas cítricas e final limpo.',
    imgPath: 'assets/imgs/beers/imagem_ipa.png',
    abv: 4.5,
    ibu: 40,
    price: 16.9,
    quantity: 48,
  },
  {
    id: 25,
    breweryId,
    name: 'Chocolate Stout',
    type: BeerTypes.STOUT,
    description:
      'Stout com cacau orgânico, notas intensas de chocolate amargo.',
    imgPath: 'assets/imgs/beers/imagem_stout.png',
    abv: 6.2,
    ibu: 35,
    price: 17.9,
    quantity: 30,
  },
  {
    id: 26,
    breweryId,
    name: 'Coconut Stout',
    type: BeerTypes.STOUT,
    description: 'Stout tropical com coco torrado e baunilha natural.',
    imgPath: 'assets/imgs/beers/imagem_stout.png',
    abv: 6.0,
    ibu: 32,
    price: 18.9,
    quantity: 25,
  },
  {
    id: 27,
    breweryId,
    name: 'Dunkel Weiss',
    type: BeerTypes.WEISS,
    description:
      'Weissbier escura com maltes torrados e especiarias tradicionais.',
    imgPath: 'assets/imgs/beers/imagem_weiss.png',
    abv: 5.3,
    ibu: 15,
    price: 15.9,
    quantity: 35,
  },
  {
    id: 28,
    breweryId,
    name: 'Honey Weiss',
    type: BeerTypes.WEISS,
    description: 'Cerveja de trigo com mel silvestre, suave e aromática.',
    imgPath: 'assets/imgs/beers/imagem_weiss.png',
    abv: 5.0,
    ibu: 13,
    price: 16.9,
    quantity: 40,
  },
  {
    id: 29,
    breweryId,
    name: 'Czech Lager',
    type: BeerTypes.LAGER,
    description: 'Lager tcheca tradicional com malte Moravia e lúpulo Saaz.',
    imgPath: 'assets/imgs/beers/imagem_lager.png',
    abv: 4.8,
    ibu: 24,
    price: 14.9,
    quantity: 45,
  },
  {
    id: 30,
    breweryId,
    name: 'Dark Lager',
    type: BeerTypes.LAGER,
    description: 'Lager escura com notas de caramelo e torrado suave.',
    imgPath: 'assets/imgs/beers/imagem_lager.png',
    abv: 5.0,
    ibu: 20,
    price: 15.9,
    quantity: 35,
  },
];

export const getBeerListFour = (breweryId: number): Beer[] => [
  {
    id: 31,
    breweryId,
    name: 'Pilsen do Sertão',
    type: BeerTypes.PILSNER,
    description:
      'Pilsen artesanal com toque de rapadura, combinando a tradição europeia com sabores do nordeste brasileiro.',
    imgPath: 'assets/imgs/beers/imagem_pilsner.png',
    abv: 4.6,
    ibu: 23,
    price: 13.9,
    quantity: 45,
  },
  {
    id: 32,
    breweryId,
    name: 'IPA Amazônica',
    type: BeerTypes.IPA,
    description:
      'IPA tropical com adição de cupuaçu e maracujá da Amazônia, equilibrando notas frutadas com amargor pronunciado.',
    imgPath: 'assets/imgs/beers/imagem_ipa.png',
    abv: 6.5,
    ibu: 60,
    price: 19.9,
    quantity: 30,
  },
  {
    id: 33,
    breweryId,
    name: 'Stout Café Mineiro',
    type: BeerTypes.STOUT,
    description:
      'Stout encorpada com café especial de Minas Gerais e cacau orgânico da Bahia, rica e aromática.',
    imgPath: 'assets/imgs/beers/imagem_stout.png',
    abv: 6.8,
    ibu: 38,
    price: 18.9,
    quantity: 25,
  },
  {
    id: 34,
    breweryId,
    name: 'Weiss Tropical',
    type: BeerTypes.WEISS,
    description:
      'Cerveja de trigo com banana-prata madura e especiarias brasileiras, refrescante e aromática.',
    imgPath: 'assets/imgs/beers/imagem_weiss.png',
    abv: 5.1,
    ibu: 14,
    price: 15.9,
    quantity: 35,
  },
  {
    id: 35,
    breweryId,
    name: 'Lager da Mata',
    type: BeerTypes.LAGER,
    description:
      'Lager leve e cristalina com ingredientes da Mata Atlântica, notas sutis de ervas nativas.',
    imgPath: 'assets/imgs/beers/imagem_lager.png',
    abv: 4.8,
    ibu: 19,
    price: 14.9,
    quantity: 40,
  },
];

export const getBeerListFive = (breweryId: number): Beer[] => [
  {
    id: 36,
    breweryId,
    name: 'Pilsen Pantaneira',
    type: BeerTypes.PILSNER,
    description:
      'Pilsen refrescante com arroz vermelho do Pantanal, proporcionando um sabor único e regional.',
    imgPath: 'assets/imgs/beers/imagem_pilsner.png',
    abv: 4.7,
    ibu: 24,
    price: 13.9,
    quantity: 38,
  },
  {
    id: 37,
    breweryId,
    name: 'IPA Catarinense',
    type: BeerTypes.IPA,
    description:
      'IPA com lúpulos cultivados em Santa Catarina, notas cítricas e florais com toque de mel de bracatinga.',
    imgPath: 'assets/imgs/beers/imagem_ipa.png',
    abv: 6.3,
    ibu: 58,
    price: 18.9,
    quantity: 42,
  },
  {
    id: 38,
    breweryId,
    name: 'Stout Capixaba',
    type: BeerTypes.STOUT,
    description:
      'Stout robusta com café do Espírito Santo e chocolate artesanal local, cremosa e intensa.',
    imgPath: 'assets/imgs/beers/imagem_stout.png',
    abv: 6.5,
    ibu: 34,
    price: 17.9,
    quantity: 28,
  },
  {
    id: 39,
    breweryId,
    name: 'Weiss Nordestina',
    type: BeerTypes.WEISS,
    description:
      'Cerveja de trigo com rapadura e especiarias do sertão, aroma tropical único.',
    imgPath: 'assets/imgs/beers/imagem_weiss.png',
    abv: 5.0,
    ibu: 13,
    price: 15.9,
    quantity: 45,
  },
  {
    id: 40,
    breweryId,
    name: 'Lager Gaúcha',
    type: BeerTypes.LAGER,
    description:
      'Lager tradicional com malte produzido no Rio Grande do Sul, sabor maltado e encorpado.',
    imgPath: 'assets/imgs/beers/imagem_lager.png',
    abv: 5.1,
    ibu: 21,
    price: 14.9,
    quantity: 50,
  },
];

export const getBeerListSix = (breweryId: number): Beer[] => [
  {
    id: 41,
    breweryId,
    name: 'Pilsen Carioca',
    type: BeerTypes.PILSNER,
    description:
      'Pilsen leve e refrescante com toque de mate, perfeita para a praia.',
    imgPath: 'assets/imgs/beers/imagem_pilsner.png',
    abv: 4.5,
    ibu: 22,
    price: 13.9,
    quantity: 55,
  },
  {
    id: 42,
    breweryId,
    name: 'IPA do Cerrado',
    type: BeerTypes.IPA,
    description:
      'IPA com pequi e frutos do cerrado, equilibrando amargor com notas frutadas nativas.',
    imgPath: 'assets/imgs/beers/imagem_ipa.png',
    abv: 6.7,
    ibu: 62,
    price: 19.9,
    quantity: 35,
  },
  {
    id: 43,
    breweryId,
    name: 'Stout Paraense',
    type: BeerTypes.STOUT,
    description:
      'Stout com cacau amazônico e castanha-do-pará, rica em sabores regionais.',
    imgPath: 'assets/imgs/beers/imagem_stout.png',
    abv: 6.4,
    ibu: 36,
    price: 18.9,
    quantity: 30,
  },
  {
    id: 44,
    breweryId,
    name: 'Weiss Praiana',
    type: BeerTypes.WEISS,
    description:
      'Weiss com coco e manga, refrescante com toques tropicais do litoral.',
    imgPath: 'assets/imgs/beers/imagem_weiss.png',
    abv: 4.9,
    ibu: 12,
    price: 15.9,
    quantity: 48,
  },
  {
    id: 45,
    breweryId,
    name: 'Lager Mineira',
    type: BeerTypes.LAGER,
    description:
      'Lager suave com toque de mel de flores silvestres de Minas Gerais.',
    imgPath: 'assets/imgs/beers/imagem_lager.png',
    abv: 4.8,
    ibu: 18,
    price: 14.9,
    quantity: 52,
  },
];

export const getBeerListSeven = (breweryId: number): Beer[] => [
  {
    id: 46,
    breweryId,
    name: 'Pilsen Paulista',
    type: BeerTypes.PILSNER,
    description:
      'Pilsen moderna com ingredientes orgânicos de pequenos produtores do interior de São Paulo.',
    imgPath: 'assets/imgs/beers/imagem_pilsner.png',
    abv: 4.8,
    ibu: 25,
    price: 14.9,
    quantity: 40,
  },
  {
    id: 47,
    breweryId,
    name: 'IPA Litorânea',
    type: BeerTypes.IPA,
    description:
      'IPA com frutas cítricas do litoral brasileiro, refrescante e aromática.',
    imgPath: 'assets/imgs/beers/imagem_ipa.png',
    abv: 6.0,
    ibu: 55,
    price: 18.9,
    quantity: 33,
  },
  {
    id: 48,
    breweryId,
    name: 'Stout Goiana',
    type: BeerTypes.STOUT,
    description:
      'Stout com café do cerrado goiano e baunilha nativa, complexa e aromática.',
    imgPath: 'assets/imgs/beers/imagem_stout.png',
    abv: 6.2,
    ibu: 32,
    price: 17.9,
    quantity: 25,
  },
  {
    id: 49,
    breweryId,
    name: 'Weiss da Serra',
    type: BeerTypes.WEISS,
    description:
      'Weiss com frutas serranas e especiarias da região sul, refrescante e equilibrada.',
    imgPath: 'assets/imgs/beers/imagem_weiss.png',
    abv: 5.2,
    ibu: 14,
    price: 16.9,
    quantity: 38,
  },
  {
    id: 50,
    breweryId,
    name: 'Lager Brasiliense',
    type: BeerTypes.LAGER,
    description:
      'Lager clean e moderna como a capital, com maltes selecionados do centro-oeste.',
    imgPath: 'assets/imgs/beers/imagem_lager.png',
    abv: 4.9,
    ibu: 20,
    price: 15.9,
    quantity: 45,
  },
];

export const getBeerListEight = (breweryId: number): Beer[] => [
  {
    id: 51,
    breweryId,
    name: 'Pilsen do Vale',
    type: BeerTypes.PILSNER,
    description:
      'Pilsen com ingredientes do Vale do Paraíba, leve e cristalina.',
    imgPath: 'assets/imgs/beers/imagem_pilsner.png',
    abv: 4.6,
    ibu: 23,
    price: 13.9,
    quantity: 44,
  },
  {
    id: 52,
    breweryId,
    name: 'IPA da Mantiqueira',
    type: BeerTypes.IPA,
    description:
      'IPA com ervas aromáticas da Serra da Mantiqueira, complexa e única.',
    imgPath: 'assets/imgs/beers/imagem_ipa.png',
    abv: 6.4,
    ibu: 59,
    price: 19.9,
    quantity: 32,
  },
  {
    id: 53,
    breweryId,
    name: 'Stout da Serra',
    type: BeerTypes.STOUT,
    description:
      'Stout com café de altitude e chocolate artesanal serrano, encorpada e rica.',
    imgPath: 'assets/imgs/beers/imagem_stout.png',
    abv: 6.6,
    ibu: 35,
    price: 18.9,
    quantity: 28,
  },
  {
    id: 54,
    breweryId,
    name: 'Weiss do Campo',
    type: BeerTypes.WEISS,
    description:
      'Weiss com trigo do interior e mel silvestre, suave e aromática.',
    imgPath: 'assets/imgs/beers/imagem_weiss.png',
    abv: 5.0,
    ibu: 13,
    price: 15.9,
    quantity: 42,
  },
  {
    id: 55,
    breweryId,
    name: 'Lager Fluminense',
    type: BeerTypes.LAGER,
    description:
      'Lager tropical com toque de frutas cítricas do interior do Rio.',
    imgPath: 'assets/imgs/beers/imagem_lager.png',
    abv: 4.7,
    ibu: 19,
    price: 14.9,
    quantity: 48,
  },
];

export const getBeerListNine = (breweryId: number): Beer[] => [
  {
    id: 56,
    breweryId,
    name: 'Pilsen da Floresta',
    type: BeerTypes.PILSNER,
    description:
      'Pilsen com ingredientes sustentáveis da Amazônia, sabor único e refrescante.',
    imgPath: 'assets/imgs/beers/imagem_pilsner.png',
    abv: 4.7,
    ibu: 24,
    price: 14.9,
    quantity: 36,
  },
  {
    id: 57,
    breweryId,
    name: 'IPA do Forte',
    type: BeerTypes.IPA,
    description:
      'IPA baiana com pitadas de dendê e especiarias locais, tropical e marcante.',
    imgPath: 'assets/imgs/beers/imagem_ipa.png',
    abv: 6.6,
    ibu: 61,
    price: 19.9,
    quantity: 30,
  },
  {
    id: 58,
    breweryId,
    name: 'Stout do Porto',
    type: BeerTypes.STOUT,
    description:
      'Stout com café porto de Santos e cacau do sul da Bahia, robusta e complexa.',
    imgPath: 'assets/imgs/beers/imagem_stout.png',
    abv: 6.5,
    ibu: 37,
    price: 18.9,
    quantity: 25,
  },
  {
    id: 59,
    breweryId,
    name: 'Weiss da Colônia',
    type: BeerTypes.WEISS,
    description:
      'Weiss com banana orgânica e especiarias de colônias alemãs do sul.',
    imgPath: 'assets/imgs/beers/imagem_weiss.png',
    abv: 5.1,
    ibu: 14,
    price: 16.9,
    quantity: 40,
  },
  {
    id: 60,
    breweryId,
    name: 'Lager do Litoral',
    type: BeerTypes.LAGER,
    description:
      'Lager clara com toque de sal marinho e limão, perfeita para o verão.',
    imgPath: 'assets/imgs/beers/imagem_lager.png',
    abv: 4.6,
    ibu: 18,
    price: 14.9,
    quantity: 52,
  },
];

export const getBeerListTen = (breweryId: number): Beer[] => [
  {
    id: 61,
    breweryId,
    name: 'Pilsen das Águas',
    type: BeerTypes.PILSNER,
    description:
      'Pilsen com água mineral do Bonito, cristalina e extremamente refrescante.',
    imgPath: 'assets/imgs/beers/imagem_pilsner.png',
    abv: 4.5,
    ibu: 22,
    price: 13.9,
    quantity: 45,
  },
  {
    id: 62,
    breweryId,
    name: 'IPA das Dunas',
    type: BeerTypes.IPA,
    description:
      'IPA com notas de frutas tropicais dos lençóis maranhenses, exótica e aromática.',
    imgPath: 'assets/imgs/beers/imagem_ipa.png',
    abv: 6.3,
    ibu: 57,
    price: 18.9,
    quantity: 35,
  },
  {
    id: 63,
    breweryId,
    name: 'Stout dos Pampas',
    type: BeerTypes.STOUT,
    description:
      'Stout com café dos campos sulinos e chocolate artesanal gaúcho.',
    imgPath: 'assets/imgs/beers/imagem_stout.png',
    abv: 6.4,
    ibu: 33,
    price: 17.9,
    quantity: 28,
  },
  {
    id: 64,
    breweryId,
    name: 'Weiss do Vale',
    type: BeerTypes.WEISS,
    description:
      'Weiss com trigo do Vale do Itajaí e especiarias locais, suave e aromática.',
    imgPath: 'assets/imgs/beers/imagem_weiss.png',
    abv: 5.0,
    ibu: 13,
    price: 15.9,
    quantity: 42,
  },
  {
    id: 65,
    breweryId,
    name: 'Lager das Montanhas',
    type: BeerTypes.LAGER,
    description:
      'Lager produzida em altitude, com maltes serranos e água de nascente.',
    imgPath: 'assets/imgs/beers/imagem_lager.png',
    abv: 4.9,
    ibu: 20,
    price: 14.9,
    quantity: 46,
  },
];

export const getBeerListEleven = (breweryId: number): Beer[] => [
  {
    id: 66,
    breweryId,
    name: 'Pilsen do Agreste',
    type: BeerTypes.PILSNER,
    description:
      'Pilsen com mandioca do agreste nordestino, sabor autêntico e regional.',
    imgPath: 'assets/imgs/beers/imagem_pilsner.png',
    abv: 4.8,
    ibu: 24,
    price: 13.9,
    quantity: 40,
  },
  {
    id: 67,
    breweryId,
    name: 'IPA do Mangue',
    type: BeerTypes.IPA,
    description:
      'IPA com toques de frutas típicas do mangue pernambucano, única e marcante.',
    imgPath: 'assets/imgs/beers/imagem_ipa.png',
    abv: 6.5,
    ibu: 60,
    price: 19.9,
    quantity: 32,
  },
  {
    id: 68,
    breweryId,
    name: 'Stout do Araguaia',
    type: BeerTypes.STOUT,
    description:
      'Stout com café do cerrado e castanhas do Araguaia, encorpada e terrosa.',
    imgPath: 'assets/imgs/beers/imagem_stout.png',
    abv: 6.6,
    ibu: 35,
    price: 18.9,
    quantity: 26,
  },
  {
    id: 69,
    breweryId,
    name: 'Weiss das Missões',
    type: BeerTypes.WEISS,
    description:
      'Weiss com trigo das antigas missões e erva-mate, tradicional com toque regional.',
    imgPath: 'assets/imgs/beers/imagem_weiss.png',
    abv: 5.2,
    ibu: 14,
    price: 16.9,
    quantity: 38,
  },
  {
    id: 70,
    breweryId,
    name: 'Lager da Fronteira',
    type: BeerTypes.LAGER,
    description:
      'Lager com maltes da fronteira sul, influência gaúcha e uruguaia.',
    imgPath: 'assets/imgs/beers/imagem_lager.png',
    abv: 4.8,
    ibu: 19,
    price: 14.9,
    quantity: 44,
  },
];

export const getBeerListTwelve = (breweryId: number): Beer[] => [
  {
    id: 71,
    breweryId,
    name: 'Pilsen da Chapada',
    type: BeerTypes.PILSNER,
    description:
      'Pilsen com água da Chapada Diamantina, pura e cristalina como os diamantes.',
    imgPath: 'assets/imgs/beers/imagem_pilsner.png',
    abv: 4.7,
    ibu: 23,
    price: 14.9,
    quantity: 42,
  },
  {
    id: 72,
    breweryId,
    name: 'IPA das Gerais',
    type: BeerTypes.IPA,
    description:
      'IPA com ervas aromáticas das Gerais, complexidade única das montanhas mineiras.',
    imgPath: 'assets/imgs/beers/imagem_ipa.png',
    abv: 6.4,
    ibu: 58,
    price: 18.9,
    quantity: 34,
  },
  {
    id: 73,
    breweryId,
    name: 'Stout da Serra do Mar',
    type: BeerTypes.STOUT,
    description:
      'Stout com café da Serra do Mar e chocolate artesanal paulista, intensa e marcante.',
    imgPath: 'assets/imgs/beers/imagem_stout.png',
    abv: 6.5,
    ibu: 36,
    price: 17.9,
    quantity: 28,
  },
  {
    id: 74,
    breweryId,
    name: 'Weiss do Cerrado',
    type: BeerTypes.WEISS,
    description:
      'Weiss com trigo do cerrado e mel de flores nativas, aroma único do Brasil central.',
    imgPath: 'assets/imgs/beers/imagem_weiss.png',
    abv: 5.1,
    ibu: 13,
    price: 15.9,
    quantity: 40,
  },
  {
    id: 75,
    breweryId,
    name: 'Lager dos Canyons',
    type: BeerTypes.LAGER,
    description:
      'Lager dos canyons do sul, com água mineral pura e maltes especiais.',
    imgPath: 'assets/imgs/beers/imagem_lager.png',
    abv: 4.9,
    ibu: 20,
    price: 14.9,
    quantity: 45,
  },
];
